CREATE TABLE J_ONELINEBOARD(
  BRD_NO NUMBER NOT NULL,
  BRD_CONTENT VARCHAR2(500) NOT NULL,
  BRD_REG_DATE DATE DEFAULT SYSDATE,
  BRD_UPDATE_DATE DATE,
  BRD_IP VARCHAR2(220) NOT NULL,
  BRD_DEL_YN CHAR(1) default 'n' check (brd_del_yn in ('y','n')),
  M_NO NUMBER NOT NULL ,
  BRD_OUT_DATE DATE
);
